Translate faq functions page
reactjs/he.reactjs.org pull request #172
Opened 2021-02-03 18:03 UTC by orrsteinberg

Translated the 'Passing Functions to Components' page in the FAQ section, as mentioned in https://github.com/reactjs/he.reactjs.org/issues/1#issuecomment-767143583

Let me know if any changes are needed. 🙂

2021-03-11 08:22 UTC, galtalmor requested changes

2021-03-11 08:22 UTC, galtalmor commented on content/docs/faq-functions.md
> +'Throttling' מונע מפונקציה להיקרא יותר מפעם אחת בתוך חלון זמן נתון. הדוגמה למטה עושה throttle למטפל אירוע לחיצה כדי למנוע מקריאה לפונקציה יותר מפעם אחת בשנייה.
```suggestion
Throttling מונע מפונקציה להיקרא יותר מפעם אחת בתוך חלון זמן נתון. הדוגמה למטה עושה throttle למטפל אירוע לחיצה כדי למנוע מקריאה לפונקציה יותר מפעם אחת בשנייה.
```

2021-03-11 08:22 UTC, galtalmor commented on content/docs/faq-functions.md
> +'Debouncing' מוודא שהפונקציה לא תוצא לפועל עד שפרק זמן מסוים חלף מאז הפעם האחרונה בה היא נקראה. זה יכול להיות שימושי כאשר אתה צריך לבצע חישוב יקר כלשהו בתגובה לאירוע שעלול להיות משוגר במהירות (למשל א
```suggestion
Debouncing מוודא שהפונקציה לא תוצא לפועל עד שפרק זמן מסוים חלף מאז הפעם האחרונה בה היא נקראה. זה יכול להיות שימושי כאשר אתה צריך לבצע חישוב יקר כלשהו בתגובה לאירוע שעלול להיות משוגר בתדירות גבוהה (למשל אירועי גלילה או הקלדה). הדוגמה למטה עושה debounce לקלט טקסט עם השהייה של 250 מילי שניות.
```

2021-03-11 08:22 UTC, galtalmor commented on content/docs/faq-functions.md
> +[`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) היא דרך לקביעת תור להוצאה לפועל של פונקציה בתוך הדפדפן בזמן האופטימלי מבחינת ביצועי רינדור. פו
```suggestion

[`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) היא דרך לקביעת תור להוצאה לפועל של פונקציה בתוך הדפדפן בזמן האופטימלי מבחינת ביצועי רינדור. פונקציה שהוכנסה לתור עם `requestAnimationFrame` תבוצע בפריים הבא. הדפדפן יעבוד קשה בכדי לוודא שישנם 60 פריימים לשנייה (60 fps). יחד עם זאת, אם הדפדפן לא מסוגל לעשות זאת, הוא *יגביל* באופן טבעי את כמות הפריימים בשנייה. לדוגמה, מכשיר מסוים עלול להיות מסוגל להתמודד רק עם 30 פריימים לשנייה כך שתקבל רק 30 פריימים באותה שנייה. שימוש ב-`requestAnimationFrame` בשביל לבצע throttling היא טכניקה שימושית בכך שהיא מונעת ממך לבצע יותר מ-60 עידכונים בשנייה. אם אתה מבצע 100 עידכונים בשנייה זה יוצר עבודה נוספת לדפדפן שהמשתמש בכל מקרה לא ייראה.
```

2021-03-11 08:22 UTC, galtalmor commented on content/docs/faq-functions.md
> +> הערה:
```suggestion

> הערה:
```

2021-03-11 08:22 UTC, galtalmor commented on content/docs/faq-functions.md
> +    // אם אנחנו מקבלים עידכונים רבים בפרק זמן קצוב, נפרסם רק את הערך העדכני ביותר.
```suggestion
    // אם אנחנו מקבלים עידכונים רבים במשך פריים אחד, נפרסם רק את הערך האחרון.
```

2021-03-11 18:35 UTC, orrsteinberg commented
Great, thank you for taking the time to review the whole thing :+1: 
Changes have been applied.

2021-03-12 06:46 UTC, galtalmor approved these changes

2021-03-12 06:47 UTC, merged

2021-03-12 06:48 UTC, galtalmor commented
@orrsteinberg Thank you for the contribution!